# Generated by Django 6.0.5 on 2026-05-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('department_name', models.CharField(max_length=255)),
                ('dashboard_title', models.CharField(max_length=255)),
                ('hod_name', models.CharField(max_length=255)),
                ('footer_left', models.TextField()),
                ('footer_right', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
