# Generated by Django 6.0.5 on 2026-05-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kpi_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
