# Generated by Django 6.0.5 on 2026-05-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_revision_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('core', models.IntegerField()),
                ('minor_track', models.IntegerField()),
                ('open_elective', models.IntegerField()),
                ('value_education', models.IntegerField()),
                ('skill_enhancement', models.IntegerField()),
                ('ability_enhancement', models.IntegerField()),
                ('elective', models.IntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SkillGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('internship', models.IntegerField()),
                ('value_education', models.IntegerField()),
                ('skill_enhancement', models.IntegerField()),
                ('ability_enhancement', models.IntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
