# Generated by Django 6.0.5 on 2026-05-24 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_creditdistribution_skillgrowth'),
    ]

    operations = [
        migrations.CreateModel(
            name='SWOTEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Strength', 'Strength'), ('Weakness', 'Weakness'), ('Opportunity', 'Opportunity'), ('Threat', 'Threat')], max_length=20)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swot_entries', to='core.revision')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
