# Generated by Django 6.0.5 on 2026-05-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_swotentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='courses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revision',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
