# Generated by Django 6.0.5 on 2026-05-24 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_revision_courses_revision_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexibilityMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core', models.IntegerField(default=0)),
                ('minor_track', models.IntegerField(default=0)),
                ('open_elective', models.IntegerField(default=0)),
                ('value_education', models.IntegerField(default=0)),
                ('skill_enhancement', models.IntegerField(default=0)),
                ('ability_enhancement', models.IntegerField(default=0)),
                ('elective', models.IntegerField(default=0)),
                ('flexibility_index', models.IntegerField(default=0)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.revision')),
            ],
        ),
    ]
