# Generated by Django 6.0.5 on 2026-05-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_flexibilitymetric'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=100)),
                ('introduced_year', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('domain', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewCourseGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('core', models.IntegerField()),
                ('elective', models.IntegerField()),
                ('skill', models.IntegerField()),
                ('experiential', models.IntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='NewCourseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_courses_added', models.IntegerField()),
                ('percentage_growth', models.IntegerField()),
                ('new_credits', models.IntegerField()),
                ('industry_facing', models.IntegerField()),
                ('courses_dropped', models.IntegerField()),
            ],
        ),
    ]
