# Generated by Django 6.0.5 on 2026-05-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_newcourse_newcoursegrowth_newcoursesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SkillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_skill_courses', models.IntegerField()),
                ('percentage_of_curriculum', models.DecimalField(decimal_places=2, max_digits=5)),
                ('previous_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('certification_tracks', models.IntegerField()),
                ('semester_skill_labs', models.IntegerField()),
                ('growth_percentage', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='skillgrowth',
            old_name='internship',
            new_name='credits',
        ),
        migrations.RemoveField(
            model_name='skillgrowth',
            name='ability_enhancement',
        ),
        migrations.RemoveField(
            model_name='skillgrowth',
            name='skill_enhancement',
        ),
        migrations.RemoveField(
            model_name='skillgrowth',
            name='value_education',
        ),
    ]
