# Generated by Django 6.0.5 on 2026-05-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_certificationtrack_skillsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverviewSkillGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('internship', models.IntegerField()),
                ('value_education', models.IntegerField()),
                ('skill_enhancement', models.IntegerField()),
                ('ability_enhancement', models.IntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterField(
            model_name='revision',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='revision',
            name='tags',
            field=models.TextField(),
        ),
    ]
