# Generated by Django 6.0.5 on 2026-05-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_overviewskillgrowth_alter_revision_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployabilityInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Employability', 'Employability'), ('Ethics', 'Ethics'), ('Sustainability', 'Sustainability')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='EmployabilitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employability_text', models.TextField()),
                ('ethics_text', models.TextField()),
                ('sustainability_text', models.TextField()),
                ('vision_statement', models.TextField()),
            ],
        ),
    ]
