# Generated by Django 6.0.5 on 2026-05-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_employabilityinitiative_employabilitysummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepreneurshipInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Entrepreneurship', 'Entrepreneurship'), ('Research', 'Research'), ('Higher Studies', 'Higher Studies')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='EntrepreneurshipSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepreneurship_text', models.TextField()),
                ('research_text', models.TextField()),
                ('higher_studies_text', models.TextField()),
                ('vision_statement', models.TextField()),
                ('notable_achievement', models.TextField(blank=True)),
            ],
        ),
    ]
