# Generated by Django 6.0.5 on 2026-05-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entrepreneurshipinitiative_entrepreneurshipsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustrySkillInitiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Platform', 'Platform'), ('Skill Domain', 'Skill Domain'), ('Project Domain', 'Project Domain')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='IndustrySkillSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_development_text', models.TextField()),
                ('tcs_text', models.TextField()),
                ('certification_text', models.TextField()),
                ('linkedin_text', models.TextField()),
                ('hackerrank_text', models.TextField()),
                ('github_text', models.TextField()),
                ('live_projects_text', models.TextField()),
                ('practical_learning_text', models.TextField()),
                ('vision_statement', models.TextField()),
            ],
        ),
    ]
