# Generated by Django 6.0.5 on 2026-05-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_industryskillinitiative_industryskillsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBenchmarkSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benchmarking_text', models.TextField()),
                ('exchange_program_text', models.TextField()),
                ('research_text', models.TextField()),
                ('impact_text', models.TextField()),
                ('student_achievement', models.TextField()),
                ('vision_statement', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
