# Generated by Django 6.0.5 on 2026-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ugccompliancescore_ugccompliancesummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGCRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=255)),
                ('year_2018', models.CharField(max_length=100)),
                ('year_2019', models.CharField(max_length=100)),
                ('year_2021', models.CharField(max_length=100)),
                ('year_2023', models.CharField(max_length=100)),
                ('year_2024', models.CharField(max_length=100)),
                ('year_2025', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UGCYearSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('interpretation', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
