# Generated by Django 6.0.5 on 2026-05-26 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_curriculumgap'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncrementalGrowthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('total_credits', models.IntegerField()),
                ('total_courses', models.IntegerField()),
                ('core_cs_credits', models.IntegerField()),
                ('internship_credits', models.IntegerField()),
                ('elective_variety', models.CharField(max_length=50)),
                ('ai_ml_courses', models.CharField(max_length=50)),
                ('hss_value_credits', models.CharField(max_length=50)),
                ('multidisciplinary', models.CharField(max_length=50)),
                ('cloud_cyber_courses', models.IntegerField()),
                ('theory_hours', models.IntegerField()),
                ('practical_hours', models.IntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='IncrementalGrowthSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=100)),
                ('total_credits', models.IntegerField()),
                ('total_courses', models.IntegerField()),
                ('core_cs_credits', models.IntegerField()),
                ('elective_variety', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MSCGrowthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('total_credits', models.IntegerField()),
                ('total_courses', models.IntegerField()),
                ('core_cs_credits', models.IntegerField()),
                ('internship_credits', models.IntegerField()),
                ('elective_variety', models.CharField(max_length=50)),
                ('ai_ml_courses', models.IntegerField()),
                ('cloud_cyber_courses', models.IntegerField()),
                ('theory_hours', models.IntegerField()),
                ('practical_hours', models.IntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
