# Generated by Django 6.0.5 on 2026-05-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_incrementalgrowthmetric_incrementalgrowthsummary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSCGrowthAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=100)),
                ('value_2021', models.CharField(max_length=100)),
                ('value_2024', models.CharField(max_length=100)),
                ('value_2025', models.CharField(max_length=100)),
                ('trend', models.CharField(max_length=100)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
