# Generated by Django 6.0.5 on 2026-05-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_electivetrack_flexibilitydimension_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectiveTrack',
        ),
        migrations.DeleteModel(
            name='FlexibilityDimension',
        ),
        migrations.DeleteModel(
            name='FlexibilityInsight',
        ),
        migrations.DeleteModel(
            name='StudentPathway',
        ),
    ]
